#!/bin/sh /etc/rc.common

USE_PROCD=1

start_service() {
	local autostart

	config_load 'devctl'
	config_get autostart devctl 'autostart' '0'

	if [ "$autostart" -eq 1 ]; then
		procd_open_instance
		procd_set_param command /usr/bin/devctl
		procd_set_param pidfile /var/run/devctl.pid
		procd_set_param file /etc/config/devctl
		procd_close_instance
	fi
}

service_triggers() {
	procd_add_reload_trigger "devctl"
}

reload_service() {
	stop
	start
}
